### ISSUE TITLE
Bot doesn't work

### ISSUE THREAD

**Issue by XuaTheGrate** [pikaninja/RoboDannyEnhcanced#5]
I tried running it and got an error: 
```python
Traceback (most recent call last):
  File "C:\Users\Xua Yraili\Documents\RoboDannyEnhcanced\bot.py", line 251, in <module>
    ctx.add_command(beans)
  File "C:\Users\Xua Yraili\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\ext\commands\core.py", line 1132, in add_command
    raise TypeError('The command passed must be a subclass of Command')
TypeError: The command passed must be a subclass of Command
```
plz help

**Comment by pikaninja** [comment]
:c

**Comment by Megadynamite** [comment]
Hi please don't delete the issue template, it is there for a reason so we know how to help you.

**Comment by daggy1234** [comment]
This has aldready been raised in #69 please do not duplicate issues.
